{
 "title": "AWS EC2 spot instance requests",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Official AWS doc",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "https://github.com/awsdocs/amazon-ec2-user-guide/blob/master/doc_source/spot-request-status.md#spot-request-status-codes"
  },
  {
   "title": "instance-requests ",
   "type": "graph",
   "description": "Spot instance requests count.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ec2_spot_instance_requests", "legendFormat": "{{ region }}" }
   ]
  },
  {
   "title": "bad-parameters",
   "type": "graph",
   "description": "One or more parameters for your Spot request are not valid (for example, the AMI you specified does not exist). The status message indicates which parameter is not valid.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ec2_spot_instance_bad_parameters_requests",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "canceled-before-fulfillment",
   "type": "graph",
   "description": "The user canceled the Spot request before it was fulfilled.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ec2_spot_instance_canceled_before_fulfillment_requests",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "fulfilled",
   "type": "graph",
   "description": "The Spot request is active, and Amazon EC2 is launching your Spot Instances.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ec2_spot_instance_fulfilled_requests",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "constraint-not-fulfillable",
   "type": "graph",
   "description": "The Spot request can't be fulfilled because one or more constraints are not valid (for example, the Availability Zone does not exist). The status message indicates which constraint is not valid.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ec2_spot_instance_constraint_not_fulfillable_requests",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "pending-fulfillment",
   "type": "graph",
   "description": "Amazon EC2 is trying to provision your Spot Instances.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ec2_spot_instance_pending_fulfillment_requests",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "az-group-constraint",
   "type": "graph",
   "description": "Amazon EC2 cannot launch all the instances you requested in the same Availability Zone.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ec2_spot_instance_az_group_contraint_requests",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "marked-for-stop",
   "type": "graph",
   "description": "The Spot Instance is marked for stopping.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ec2_spot_instance_marked_for_stop_requests",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "marked-for-termination",
   "type": "graph",
   "description": "The Spot Instance is marked for termination.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ec2_spot_instance_marked_for_termination_requests",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "capacity-not-available",
   "type": "graph",
   "description": "There is not enough capacity available for the instances that you requested.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ec2_spot_instance_capacity_not_available_requests",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "instance-stopped-no-capacity",
   "type": "graph",
   "description": "Your instance was stopped because there was no longer enough Spot capacity available for the instance.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ec2_spot_instance_stopped_no_capacity_requests",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "instance-terminated-no-capacity",
   "type": "graph",
   "description": "Your instance was terminated because there is no longer enough Spot capacity available for the instance.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ec2_spot_instance_terminated_no_capacity_requests",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "price-too-low",
   "type": "graph",
   "description": "The request can't be fulfilled yet because your maximum price is below the Spot price. In this case, no instance is launched and your request remains open.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ec2_spot_instance_price_too_low_requests",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "instance-stopped-by-price",
   "type": "graph",
   "description": "Your instance was stopped because the Spot price exceeded your maximum price.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ec2_spot_instance_stopped_by_price_requests",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "instance-terminated-by-price",
   "type": "graph",
   "description": "Your instance was terminated because the Spot price exceeded your maximum price. If your request is persistent, the process restarts, so your request is pending evaluation.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ec2_spot_instance_terminated_by_price_requests",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "launch-group-constraint",
   "type": "graph",
   "description": "Amazon EC2 cannot launch all the instances that you requested at the same time. All instances in a launch group are started and terminated together.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ec2_spot_instance_launch_group_constraint_requests",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "pending-evaluation",
   "type": "graph",
   "description": "After you make a Spot Instance request, it goes into the pending-evaluation state while the system evaluates the parameters of your request.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ec2_spot_instance_pending_evaluation_requests",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "request-canceled-and-instance-running",
   "type": "graph",
   "description": "You canceled the Spot request while the Spot Instances are still running. The request is cancelled, but the instances remain running.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ec2_spot_instance_request_canceled_and_instance_running_requests",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "not-scheduled-yet",
   "type": "graph",
   "description": "The Spot request is not evaluated until the scheduled date.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ec2_spot_instance_not_scheduled_yet_requests",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "instance-terminated-launch-group-constraint",
   "type": "graph",
   "description": "One or more of the instances in your launch group was terminated, so the launch group constraint is no longer fulfilled.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ec2_spot_instance_terminated_launch_group_constraint_requests",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "placement-group-constraint",
   "type": "graph",
   "description": "The Spot request can't be fulfilled yet because a Spot Instance can't be added to the placement group at this time.\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ec2_spot_instance_placement_group_constraint_requests",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "instance-terminated-by-schedule",
   "type": "graph",
   "description": "Your Spot Instance was terminated at the end of its scheduled duration.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ec2_spot_instance_terminated_by_schedule_requests",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "instance-stopped-by-user",
   "type": "graph",
   "description": "Your instance was stopped because a user stopped the instance or ran the shutdown command from the instance.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ec2_spot_instance_stopped_by_user_requests",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "instance-terminated-by-user",
   "type": "graph",
   "description": "You terminated a Spot Instance that had been fulfilled, so the request state is closed (unless it's a persistent request) and the instance state is terminated.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ec2_spot_instance_terminated_by_user_requests",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "system-error",
   "type": "graph",
   "description": "There was an unexpected system error. If this is a recurring issue, please contact AWS Support for assistance.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ec2_spot_instance_system_error_requests",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "schedule-expired",
   "type": "graph",
   "description": "The Spot request expired because it was not fulfilled before the specified date.\n\n",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ec2_spot_instance_schedule_expired_requests",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "instance-terminated-by-service",
   "type": "graph",
   "description": "Your instance was terminated from a stopped state.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ec2_spot_instance_terminated_by_service_requests",
     "legendFormat": "{{ region }}"
    }
   ]
  }
 ]
}